server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Erik-Yim/spring_cloud_demo/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: erik_yim@aliyun.com                                          # git仓库的账号
          password: yanjiayang1010                                            # git仓库的密码